name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "15"
          feed_list: "https://node2.feed43.com/nuistsmsweeklyseminar.xml,https://node2.feed43.com/tsinghuadessseminar.xml,https://node2.feed43.com/hohaicooseminar.xml,https://node2.feed43.com/sjtusooseminar.xml,https://node2.feed43.com/sustechdoseseminar.xml,https://node2.feed43.com/klocwqdioseminar.xml,https://node2.feed43.com/ltoweeklyseminar.xml,https://node2.feed43.com/soedseminar.xml,https://node2.feed43.com/lasgseminar.xml"